name: C/C++ CI



on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: msfjarvis/setup-android@0.2
        with:
          # Gradle tasks to run - If you want to run ./gradlew assemble, specify assemble here. 
          gradleTasks: assemble# optional, default is assembleDebug
      - name: Android NDK toolchain Setup
      - uses: ravinderjangra/android-ndk-toolchain-setup@0.1
        with:
          api: 16
          arch: armbi-v8a
          install-location: ../
      - name: build_android_lua53
        run: ./build/make_android_lua53.sh
